name: Delete a serverless container in Yandex Cloud

inputs:
  container-id:
    type: string
    required: true
    description: ID of the container to delete
  sa-key:
    type: string
    required: true
    description: Service account private key
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.container-id }}
    - ${{ inputs.sa-key }}
